name: CI

on:
  push:
    branches:
      - main
      - changeset-release/main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Format, Lint, Test & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/build
        with:
          build: true
          token: ${{ secrets.GITHUB_TOKEN }}

  e2e-components:
    name: 🧪 Component Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      HUSKY: 0
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/e2e-setup
      - uses: ./.github/workflows/actions/e2e-components

  e2e-visual:
    name: 🧪 Visual Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      HUSKY: 0
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/e2e-setup
      - uses: ./.github/workflows/actions/e2e-visual
