name: CI

on:
  push:
    branches:
      - main
      - changeset-release/main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Build Design System
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/actions/build
        with:
          build: true
