name: CI

on:
  push:
    branches:
      - main
      - changeset-release/main
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Build Design System
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: 👷 Build Design System
        uses: ./.github/workflows/actions/build
        with:
          build: true
