name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stetup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Update NPM registry path
        run: npm run registry
      - name: Clean install
        run: npm ci
      - name: Define Nx cache
        uses: nrwl/nx-set-shas@v4

      - name: Prepare build
        run: npx nx run-many -t prepare

      - name: Check format
        run: npx nx-cloud record -- nx format:check

      - name: Lint, test & build
        run: npx nx affected -t lint test build
