name: 📸 Create Base Image by File

on:
  issue_comment:
    types: [created]

jobs:
  CreateSnapshot:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/create-base-image')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Get Action URL
        id: action-url
        run: echo "url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Check for /create-base-image command
        uses: actions/github-script@v5
        id: command
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const comment = context.payload.comment.body.trim();
            const regex = /\/create-base-image(?:\s+(.*))?/;
            if (regex.test(comment)) {
              const match = comment.match(regex);
              const imageName = match[1] ? match[1].trim() : '';
              console.log(`Detected /create-base-image command with argument: ${imageName}`);
              // Set the output variable
              return imageName;
            }
            return ''

      - name: Get result
        run: echo "${{ steps.command.outputs.result }}"

      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     comment-id: ${{ github.event.comment.id }}
      #     edit-mode: replace
      #     body: |
      #       **📸 Create Base Image in Progress...**

      #       [Check out the release on GitHub ↗︎](${{ steps.action-url.outputs.url }})

