name: 📦️ Pre-Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  BAL_PUBLISH_DS: false

jobs:
  Release:
    name: 📦️ Pre-Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/release-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: '📦️ Pre-Release'
          commit: 'prepare release'
          createGithubReleases: false
          publish: echo "Publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
