name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/release-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - uses: ./.github/workflows/actions/release-build

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     publish: npm run release
      #   env:
      #     HUSKY_DISABLED: 1
      #     BAL_DS_RELEASE: true
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # - name: Echo Changeset output
      #   shell: bash
      #   run: |
      #     echo "Changeset published - ${{ steps.changesets.outputs.published }}"
      #     echo "Changeset publishedPackages - ${{ steps.changesets.outputs.publishedPackages }}"
      #     echo "Changeset hasChangesets - ${{ steps.changesets.outputs.hasChangesets }}"
      #     echo "Changeset pullRequestNumber - ${{ steps.changesets.outputs.pullRequestNumber }}"

      # - name: Update lock file
      #   if: steps.changesets.outputs.published == 'true'
      #   run: npm install
      #   shell: bash

      # - name: Commit lock file
      #   if: steps.changesets.outputs.published == 'true'
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: 'package-lock.json'
      #     message: 'chore(): update lock file'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag release
      #   if: steps.changesets.outputs.published == 'true'
      #   uses: thejeff77/action-push-tag@v1.0.0
      #   with:
      #     tag: 'v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}'
      #     message: 'v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}'

      # - name: Update changelog file
      #   if: steps.changesets.outputs.published == 'true'
      #   run: awk 'NR==1 {print "# Changelog"} NR!=1' packages/components/CHANGELOG.md > CHANGELOG.md
      #   shell: bash

      # - name: Commit changelog
      #   if: steps.changesets.outputs.published == 'true'
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: 'CHANGELOG.md'
      #     message: 'chore(): update changelog'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Merge main -> production
      #   if: steps.changesets.outputs.published == 'true'
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: main
      #     target_branch: production
      #     message: ':bookmark: release: ${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
