name: 📸 Create All Base Images

on:
  workflow_dispatch:

jobs:
  main:
    name: 📸 Updating Screenshots
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/e2e-build
        with:
          build: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: node ./web-server.js
          wait-on: 'http://localhost:3333'
          working-directory: e2e
          install: false
          browser: chrome
          spec: |
            cypress/e2e/visual/*.cy.ts
        env:
          CYPRESS_visualRegressionType: base
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-snapshots
          path: e2e/cypress/snapshots

      - name: Commit base images
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update base images'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
